name: tasksync
description: A collaborative task management app built with Flutter and Firebase
publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  # riverpod: ^2.4.0 # alternative (uncomment if you prefer)

  # Firebase Core
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1 # only if file uploads are needed

  # UI Components
  flutter_slidable: ^4.0.1     # swipe actions for task list
  flutter_colorpicker: ^1.0.3  # project/task colors
  intl: ^0.20.2                # date formatting
  connectivity_plus: ^4.0.1

  # Networking (if you later use REST API backend instead of Firebase)
  http: ^1.1.0
  dio: ^5.3.0

  # Local Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

  # Utilities
  uuid: ^4.5.1
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
