// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6v5QYb6ggBonmV-j5uBC2LmuSWNflCH0',
    appId: '1:453626112148:web:436a757163bffd42532c81',
    messagingSenderId: '453626112148',
    projectId: 'appdev-d37d1',
    authDomain: 'appdev-d37d1.firebaseapp.com',
    storageBucket: 'appdev-d37d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXmPYtxjjV0816XEiFd3SYyyimeZ0hOc',
    appId: '1:453626112148:android:fc33fda339c70274532c81',
    messagingSenderId: '453626112148',
    projectId: 'appdev-d37d1',
    storageBucket: 'appdev-d37d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmyX_yHs8M84TWdwXiucyXeXD53i35co',
    appId: '1:453626112148:ios:9edae215f08426e0532c81',
    messagingSenderId: '453626112148',
    projectId: 'appdev-d37d1',
    storageBucket: 'appdev-d37d1.firebasestorage.app',
    iosBundleId: 'com.example.tasksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtmyX_yHs8M84TWdwXiucyXeXD53i35co',
    appId: '1:453626112148:ios:9edae215f08426e0532c81',
    messagingSenderId: '453626112148',
    projectId: 'appdev-d37d1',
    storageBucket: 'appdev-d37d1.firebasestorage.app',
    iosBundleId: 'com.example.tasksync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6v5QYb6ggBonmV-j5uBC2LmuSWNflCH0',
    appId: '1:453626112148:web:54c016d21e997dbf532c81',
    messagingSenderId: '453626112148',
    projectId: 'appdev-d37d1',
    authDomain: 'appdev-d37d1.firebaseapp.com',
    storageBucket: 'appdev-d37d1.firebasestorage.app',
  );
}
